### ISSUE TITLE
Testing Login Flow / #6 “Log me out of other devices” not working

### ISSUE THREAD

**Issue by adriantofan** [facebookarchive/ios-howtos#8]
Hello,

In your Testing your Login Flow there is a step 6 as follows:

> 1. Someone changes the Facebook password after logging in with Facebook to your app
>    In this case, your token will be invalid and you should notify users that their Facebook session has >expired and ask them to log in again.
> 
> Change your Facebook password and select “Log me out of other devices”
> Go to your app and tap on the "Log in with Facebook” button
> Tap OK to accept the read permissions (and OK again to accept write permissions where applicable)
> Go to app settings on Facebook and verify that the granted permissions are there

So I did with my app and with FBLoginCustomLoginUISample. Unfortunately this doesn't seem to work. 
Once loged in the app, I go to Facebook, change my password and select “Log me out of other devices”. Next  I restart the app.
The app detects FBSessionStateCreatedTokenLoaded and makes the call to refresh the token without UI. The call succeeds so the session transitions in to FBSessionStateOpen, which is not correct.

Is this a bug in the sample code or in the FB single sign in process which fails to invalidate the active sessions? Am I doing something wrong?  

Thank you

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by caabernathy** [comment]
This sample is for an old version of the SDK and could likely be the reason you're running into an issue. If you're still seeing an issue in your own app, you should file a bug on https://developers.facebook.com/bugs
